#!/bin/bash
set -e

read CPU USER NICE SYSTEM IDLE IOWAIT IRQ SOFTIRQ STEAL GUEST GUEST_NICE < /proc/stat

TOTAL=$((USER+NICE+SYSTEM+IDLE+IOWAIT+IRQ+SOFTIRQ+STEAL+GUEST+GUEST_NICE))
IDLE=$((IDLE+IOWAIT))
DIFF_USAGE=$((100*(TOTAL - IDLE)/TOTAL))

echo " ${DIFF_USAGE}%"
